version: '3.3'
services:
  node-server:
    container_name: node-server
    build:
        context: ./server
        dockerfile: Dockerfile
    volumes:
        - ./server/:/usr/src/app/server
        - /app/node_modules
    ports:
      - "5000:5000"
